### ISSUE TITLE
The question about batch_size in training process of swin_lte

### ISSUE THREAD

**Issue by WenhaoYao** [jaewon-lee-b/lte#15]
Thank you for your available code, we trained the SwinIR-LTE model with a batch size of 8 but got close to 0.2dB lower compared to the results reported in the paper, I would like to inquire if the batch size has a significant impact on the model training during the training process. Appreciate your help

**Comment by jaewon-lee-b** [comment]
Hello @WenhaoYao 

LTE is sensitive to training batch size as most of the other super-resolution models.
In theory, a large batch size generates almost an actual gradient. However, in reality, increasing batch size may not improve your model performance. (I do not know the exact reason, but maybe from the optimizer or dataset distribution)

So, I would say there exists an optimum batch size for each model, and LTE for SwinIR was 32. And it is also a fair comparison since the original SwinIR uses batch size 32.
