### ISSUE TITLE
Questions about DIV2K dataset

### ISSUE THREAD

**Issue by RisingEntropy** [jaewon-lee-b/lte#19]
It is mentioned in your paper that the low-resolution images are down-sampled high-resolution images using pytorch. Are you using torch.nn.functional.interploate? The low-resolution images I generated using MATLAB's imresize function performed very well on the network with edsr or rdn as the backbone, but performed very poorly on the network with swinir as the backbone.

**Comment by jaewon-lee-b** [comment]
Hello @RisingEntropy 

Your question needs to be clarified. Do you want to know about the downsampling method? Or SwinIR bug?

1. Downsampling method - transforms.Resize
 - I confirmed that the Jacobian characteristic of this resizing function of the torch is different from that of the Matlab downsampling function. But for rectangular or square SR, it does not matter. Even though we train LTE with this function, we can apply LTE to images resized by Matlab.

2. SwinIR bug
- If LTE works for edsr or rdn, the problem is not caused by training. I think some bugs are in there.

**Comment by RisingEntropy** [comment]
Hellow @jaewon-lee-b 
I use the following command:
>python demo.py --input ./demo/Urban100_img012x2.png --model swinir-lte.pth --scale 2 --output output.png --gpu 0

And the psnr between gt and the output is only 29.1195(I use torchmetrics.image.PeakSignalNoiseRatio and set datarange to 1).
Is there anything wrong? Or simply the swinir bug in demo.py? Thanks for your reply!

**Comment by jaewon-lee-b** [comment]
You have to specify window size

**Comment by RisingEntropy** [comment]
This should be this. It seems that I need to modify demo.py. Thank you very much for your reply! I'll close this issue.
