### ISSUE TITLE
oom on GPU card when testing

### ISSUE THREAD

**Issue by crisnv** [jaewon-lee-b/lte#3]
Hello,

I am able to replicate training, but testing is causing OOM in my GPU card. 
Can you describe the GPU used for testing?

thanks

**Comment by jaewon-lee-b** [comment]
Hi @crisnv,

We confirmed that our LTE+ consumes 14GB (including cache memory) when testing the Set5 X2 task under NVIDIA RTX 3090 24GB. 

Although LTE+ is an optimized version of LTE, that model still consumes large memory when evaluating images with many query points.
I have two suggestions for evaluation.

(1) In lines 40~45 in test.py, parameters for data normalization are located on the GPU. Please try to normalize data on the CPU.
(2) Consider using LTE instead of LTE+ for evaluation. It may consume less memory while increasing computation time.

p.s. Memory fraction option in torch may resolve this issue.
