### ISSUE TITLE
Ringing Artifacts Against White Background

### ISSUE THREAD

**Issue by progwiz** [jaewon-lee-b/lte#5]
Hi,

I am noticing some overshoot artifacts around edges against white pixels for 2x EDSR model. Do you think this is related to the Gibbs phenomenon? Is there any way past this?

Really appreciate your help.

Thank you.

(The first image is 2x super-resolved and the lower is the original)

![image](https://user-images.githubusercontent.com/29153334/176066600-dc188d0a-1c42-4459-9c2c-bbe13c773088.png)

![image](https://user-images.githubusercontent.com/29153334/176066662-c84d4edd-e046-4f38-b433-94f553cead0e.png)

**Comment by jaewon-lee-b** [comment]
Hi @progwiz
You are right, that is the Gibbs phenomenon.
I hypothesis negative coefficients of convolutional layers might cause such kinds of artifacts. 
(Convolution with neg-coeff works like a high-pass filter)

A deformable convolution [1] can resolve this issue because a learnable bilinear layer has only positive coefficients (0< coeff <1).

[1] https://openaccess.thecvf.com/content_iccv_2017/html/Dai_Deformable_Convolutional_Networks_ICCV_2017_paper.html

**Comment by progwiz** [comment]
Thank you for your help! This type of artifact seems to be suppressed (though still relevant) in "real" super-resolution pipelines (eg: Real-ESRGAN). The degradation model seems like the critical difference.

For a quick solution, I was able to get past this problem with some simple post-processing.
